import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { generateTeacherReportPdf } from '../src/services/teacherReportPdf';
import { calculateTeacherGrade, percentageToPrivateGrade } from '../src/services/teacherGrade';
import { Practice, PracticeSubmissionPayload } from '../src/types';

const stages = ['problem', 'idea', 'design', 'prototype', 'error', 'redesign'].map(id => ({ id, title: id.toUpperCase(), guidingQuestion: '¿Qué ocurrió?', instructions: [], relatedStepNumbers: [], responseFields: [{ id: 'answer', prompt: 'Respuesta' }] })) as any;
const practice = { id: 't1-act1', tomo: 1, courseId: 'aprende-ia-jugando', number: 1, title: 'Práctica con acentos y ñ', description: 'Descripción', requiredMaterials: [], steps: [{ stepNumber: 1, title: 'Paso técnico', instructions: [] }], progressWallStages: stages } as Practice;
const payload = { submissionId: 'sub_12345', studentName: 'Luis Martínez Ñ', studentGroup: '5° A', studentDate: '2026-08-30', practiceId: practice.id, practiceTitle: practice.title, practiceNumber: 'Práctica 05', courseId: practice.courseId, courseTitle: 'Curso de IA', timestamp: new Date().toISOString(), formattedDate: '30 de agosto de 2026', recipients: [], totalSteps: 1, completedStepsCount: 1, steps: [{ stepNumber: 1, title: 'Paso técnico', completed: true }], status: 'COMPLETADO' } as PracticeSubmissionPayload;
const longText = 'Respuesta extensa con acentos, eñes y explicación pedagógica. '.repeat(500);
const grade = calculateTeacherGrade({ steps: { completed: 1, available: 1 }, wall: { completed: 6, available: 6 }, openQuestions: { completed: 0, available: 0 }, quiz: { completed: 0, available: 0 }, experimentsReflection: { completed: 0, available: 0 } });
const receipt = generateTeacherReportPdf({ payload, practice, wallResponses: Object.fromEntries(stages.map((stage: any) => [`${stage.id}:answer`, longText])), openQuestionAnswers: { pregunta: 'Sí funcionó correctamente.' }, evidenceLinks: [{ id: '1', name: 'evidencia.png', url: 'https://drive.google.com/file/d/1/view' }], grade, confirmedAt: '2026-08-30T12:00:00.000Z' });
assert.ok(receipt.blob.size > 1000);
mkdirSync('tmp/pdfs', { recursive: true });
writeFileSync('tmp/pdfs/comprobante-validacion.pdf', Buffer.from(await receipt.blob.arrayBuffer()));
assert.ok(receipt.pageCount > 1, 'Long answers did not create additional pages');
assert.match(receipt.fileName, /^Reporte_Docente_Practica_05_Luis_Martinez_N_5_A_2026-08-30_sub_12345\.pdf$/);
const source = readFileSync('src/services/teacherReportPdf.ts', 'utf8');
assert.ok(source.includes('Sección sin respuestas'));
assert.ok(source.includes("answer.answered ?") && source.includes("'Sin responder'"), 'Quiz does not distinguish unanswered questions');
assert.ok(source.includes('Calificación privada') && source.includes('Reporte privado para uso exclusivo del docente.'));
for (const forbidden of ['URL.createObjectURL', 'downloadReceiptPdf', 'window.open', 'localStorage', 'sessionStorage', 'indexedDB']) assert.ok(!source.includes(forbidden), `Teacher report contains forbidden ${forbidden}`);
const modal = readFileSync('src/components/SubmitPracticeModal.tsx', 'utf8');
assert.ok(modal.includes("res.state === 'confirmed'"));
assert.ok(modal.includes('academic-session-cleared'));
assert.ok(modal.lastIndexOf('generateTeacherReportPdf') > modal.indexOf("res.state === 'confirmed'"));
for (const forbidden of ['downloadReceiptPdf', 'receiptPdf', 'Volver a descargar', 'createObjectURL', 'window.open', 'Generando tu comprobante', 'Calificación Test']) assert.ok(!modal.includes(forbidden), `Student UI contains forbidden ${forbidden}`);
for (const [percentage, expected] of [[30, 6], [31, 7], [60, 7], [61, 8], [80, 8], [81, 9], [99, 9], [100, 10]] as const) assert.equal(percentageToPrivateGrade(percentage), expected);
assert.ok(Math.abs(grade.components.reduce((sum, component) => sum + component.weight, 0) - 100) < 0.001, 'Redistributed weights do not sum to 100%');
assert.deepEqual(grade.components.map(component => component.id), ['steps', 'wall'], 'Unavailable sections were not removed before redistribution');
console.log('Teacher PDF audit passed: private grading, redistribution, confirmed-only generation, safe filename, no browser download, and memory-only report flow.');
